/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author kshit
 */
public class CreatePerson extends javax.swing.JPanel {

    /**
     * Creates new form CreatePerson
     */
    Person person;
    public CreatePerson( Person person) {
        initComponents();
        this.person = person;
    }

  

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        tDob = new javax.swing.JTextField();
        tTelephone = new javax.swing.JTextField();
        tFAX = new javax.swing.JTextField();
        tEmailAddr = new javax.swing.JTextField();
        tSSN = new javax.swing.JTextField();
        tLinkedin = new javax.swing.JTextField();
        tIPAddr = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        tLocation = new javax.swing.JTextField();
        lName = new javax.swing.JLabel();
        lLocation = new javax.swing.JLabel();
        lDob = new javax.swing.JLabel();
        lTelephone = new javax.swing.JLabel();
        lFAX = new javax.swing.JLabel();
        lEmailAddr = new javax.swing.JLabel();
        lSSN = new javax.swing.JLabel();
        lLinkedin = new javax.swing.JLabel();
        lIPAddr = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        lTitle.setText("Create Personal Details");

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        lName.setText("Name:");

        lLocation.setText("Location:");

        lDob.setText("Date of Birth:");

        lTelephone.setText("Telephone No:");

        lFAX.setText("FAX No:");

        lEmailAddr.setText("Email Address:");

        lSSN.setText("SSN:");

        lLinkedin.setText("LinkedIn ID:");

        lIPAddr.setText("IP Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lName)
                            .addComponent(lLocation)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lTelephone)
                                .addComponent(lDob))
                            .addComponent(lFAX)
                            .addComponent(lEmailAddr)
                            .addComponent(lLinkedin)
                            .addComponent(lIPAddr)
                            .addComponent(lSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bSave))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tName)
                                .addComponent(tLocation)
                                .addComponent(tDob)
                                .addComponent(tTelephone)
                                .addComponent(tFAX)
                                .addComponent(tEmailAddr)
                                .addComponent(tSSN)
                                .addComponent(tLinkedin)
                                .addComponent(tIPAddr, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFAX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEmailAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmailAddr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLinkedin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIPAddr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSave)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
        person.setFname(tName.getText());
        person.setLocation(tLocation.getText());
        person.setDateOfBirth(tDob.getText());
        person.setTelephoneNo(tTelephone.getText());
        person.setFaxNo(tFAX.getText());
        person.setEmailAdress(tEmailAddr.getText());
        person.setSocialSecurityNo(tSSN.getText());
        person.setLinkedin(tLinkedin.getText());
        person.setIpAddr(tIPAddr.getText());
        JOptionPane.showMessageDialog(this,"Information Saved");
    }//GEN-LAST:event_bSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lDob;
    private javax.swing.JLabel lEmailAddr;
    private javax.swing.JLabel lFAX;
    private javax.swing.JLabel lIPAddr;
    private javax.swing.JLabel lLinkedin;
    private javax.swing.JLabel lLocation;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lSSN;
    private javax.swing.JLabel lTelephone;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tDob;
    private javax.swing.JTextField tEmailAddr;
    private javax.swing.JTextField tFAX;
    private javax.swing.JTextField tIPAddr;
    private javax.swing.JTextField tLinkedin;
    private javax.swing.JTextField tLocation;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tSSN;
    private javax.swing.JTextField tTelephone;
    // End of variables declaration//GEN-END:variables
}
