/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.BankAcc;

/**
 *
 * @author kshit
 */
public class CreateBankAcc extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAcc
     */
     BankAcc bankAcc;
    public CreateBankAcc( BankAcc bankAcc) {
        initComponents();
        this.bankAcc= bankAcc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lSavingAccNo = new javax.swing.JLabel();
        lChecAccNo = new javax.swing.JLabel();
        lRoutingNo = new javax.swing.JLabel();
        lAccName = new javax.swing.JLabel();
        tSavingAccNo = new javax.swing.JTextField();
        tChecAccNo = new javax.swing.JTextField();
        tRoutingNo = new javax.swing.JTextField();
        tAccName = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();

        lTitle.setText("Create Bank Account Details");

        lSavingAccNo.setText("Savings Account No:");

        lChecAccNo.setText("Checking Account No:");

        lRoutingNo.setText("Routing No:");

        lAccName.setText("Account Holder Name:");

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lAccName)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lRoutingNo)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lChecAccNo)
                                            .addComponent(lSavingAccNo))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tSavingAccNo)
                                    .addComponent(tChecAccNo)
                                    .addComponent(tRoutingNo)
                                    .addComponent(tAccName))))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSavingAccNo)
                    .addComponent(tSavingAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lChecAccNo)
                    .addComponent(tChecAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRoutingNo)
                    .addComponent(tRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAccName)
                    .addComponent(tAccName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bSave)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
         
         bankAcc.setSavingAccNo(tSavingAccNo.getText());
         bankAcc.setCheckingAccNo(tChecAccNo.getText());
         bankAcc.setAccHolderName(tAccName.getText());
         bankAcc.setRoutingNo(tRoutingNo.getText());
          JOptionPane.showMessageDialog(this,"Information Saved");
    }//GEN-LAST:event_bSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lAccName;
    private javax.swing.JLabel lChecAccNo;
    private javax.swing.JLabel lRoutingNo;
    private javax.swing.JLabel lSavingAccNo;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tAccName;
    private javax.swing.JTextField tChecAccNo;
    private javax.swing.JTextField tRoutingNo;
    private javax.swing.JTextField tSavingAccNo;
    // End of variables declaration//GEN-END:variables
}
