/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Device;

/**
 *
 * @author kshit
 */
public class CreateDevice extends javax.swing.JPanel {

    /**
     * Creates new form CreateDevice
     */
    Device device;
    public CreateDevice(Device device) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lDeviceBrand = new javax.swing.JLabel();
        lDeviceModel = new javax.swing.JLabel();
        lDeviceIMEINo = new javax.swing.JLabel();
        tDeviceBrand = new javax.swing.JTextField();
        tDeviceModel = new javax.swing.JTextField();
        tDeviceIMEINo = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();

        lTitle.setText("Create Device Details");

        lDeviceBrand.setText("Device Brand:");

        lDeviceModel.setText("Device Model:");

        lDeviceIMEINo.setText("Device IMEI No:");

        tDeviceModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDeviceModelActionPerformed(evt);
            }
        });

        bSave.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lDeviceBrand)
                                    .addComponent(lDeviceModel)
                                    .addComponent(lDeviceIMEINo))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tDeviceBrand)
                                    .addComponent(tDeviceModel)
                                    .addComponent(tDeviceIMEINo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(bSave)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDeviceBrand)
                    .addComponent(tDeviceBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDeviceModel)
                    .addComponent(tDeviceModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDeviceIMEINo)
                    .addComponent(tDeviceIMEINo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bSave)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tDeviceModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDeviceModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDeviceModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lDeviceBrand;
    private javax.swing.JLabel lDeviceIMEINo;
    private javax.swing.JLabel lDeviceModel;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tDeviceBrand;
    private javax.swing.JTextField tDeviceIMEINo;
    private javax.swing.JTextField tDeviceModel;
    // End of variables declaration//GEN-END:variables
}
