/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.BankAcc;

/**
 *
 * @author kshit
 */
public class ViewBankAcc extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankAcc
     */
     BankAcc bankAcc;
    public ViewBankAcc( BankAcc bankAcc) {
        initComponents();
        this.bankAcc= bankAcc;
        displayBankAcc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        lSavingAccNo = new javax.swing.JLabel();
        lChecAccNo = new javax.swing.JLabel();
        lRoutingNo = new javax.swing.JLabel();
        lAccName = new javax.swing.JLabel();
        tSavingAccNo = new javax.swing.JTextField();
        tChecAccNo = new javax.swing.JTextField();
        tRoutingNo = new javax.swing.JTextField();
        tAccName = new javax.swing.JTextField();

        lTitle.setText("View Bank Account Details");

        lSavingAccNo.setText("Savings Account No:");

        lChecAccNo.setText("Checking Account No:");

        lRoutingNo.setText("Routing No:");

        lAccName.setText("Account Holder Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(lTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lAccName)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lRoutingNo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lChecAccNo)
                                        .addComponent(lSavingAccNo))))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tSavingAccNo)
                                .addComponent(tChecAccNo)
                                .addComponent(tRoutingNo)
                                .addComponent(tAccName))))
                    .addGap(88, 88, 88)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(lTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lSavingAccNo)
                        .addComponent(tSavingAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lChecAccNo)
                        .addComponent(tChecAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lRoutingNo)
                        .addComponent(tRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lAccName)
                        .addComponent(tAccName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAccName;
    private javax.swing.JLabel lChecAccNo;
    private javax.swing.JLabel lRoutingNo;
    private javax.swing.JLabel lSavingAccNo;
    private javax.swing.JLabel lTitle;
    private javax.swing.JTextField tAccName;
    private javax.swing.JTextField tChecAccNo;
    private javax.swing.JTextField tRoutingNo;
    private javax.swing.JTextField tSavingAccNo;
    // End of variables declaration//GEN-END:variables

    private void displayBankAcc() {
       
       tAccName.setText(bankAcc.getAccHolderName());
       tChecAccNo.setText(bankAcc.getCheckingAccNo());
       tRoutingNo.setText(bankAcc.getRoutingNo());
       tSavingAccNo.setText(bankAcc.getSavingAccNo());
    }
}
