/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import car_service.Car;
import car_service.CarHistory;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

/**
 *
 * @author kshit
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    CarHistory history;
    
    public CreateJPanel(CarHistory history) {
        initComponents();
        
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblManufacturingYear = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblSeatCount = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblCertificateNumber = new javax.swing.JLabel();
        lblCertificateExpDate = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtSeatCount = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtCertificateNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblCarAvailable = new javax.swing.JLabel();
        chkCertValid = new javax.swing.JCheckBox();
        chkCertExp = new javax.swing.JCheckBox();
        chkAvlYes = new javax.swing.JCheckBox();
        chkAvlNo = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(102, 153, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Car Details");

        lblManufacturer.setText("Manufacturer");

        lblManufacturingYear.setText("Manufacturing Year");

        lblModelNumber.setText("Model Number");

        lblSerialNumber.setText("Serial Number");

        lblSeatCount.setText("Seat Count");

        lblCity.setText("City");

        lblCertificateNumber.setText("Certificate Number");

        lblCertificateExpDate.setText("Certificate Expiration Date");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCarAvailable.setText("Vehicle Available");

        chkCertValid.setText("Valid");
        chkCertValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCertValidActionPerformed(evt);
            }
        });

        chkCertExp.setText("Expired");

        chkAvlYes.setText("Yes");

        chkAvlNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCarAvailable)
                    .addComponent(lblCertificateExpDate)
                    .addComponent(lblCertificateNumber)
                    .addComponent(lblCity)
                    .addComponent(lblSeatCount)
                    .addComponent(lblSerialNumber)
                    .addComponent(lblModelNumber)
                    .addComponent(lblManufacturingYear)
                    .addComponent(lblManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtManufacturer)
                        .addComponent(txtManufacturingYear, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(txtSeatCount, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addComponent(txtCertificateNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCertValid)
                            .addComponent(chkAvlYes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCertExp)
                            .addComponent(chkAvlNo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnSave)))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturingYear)
                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeatCount)
                    .addComponent(txtSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCertificateNumber)
                    .addComponent(txtCertificateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCertificateExpDate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkCertValid)
                        .addComponent(chkCertExp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarAvailable)
                    .addComponent(chkAvlYes)
                    .addComponent(chkAvlNo))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(449, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String manufacturer = txtManufacturer.getText();
        int manufacturingYear = Integer.parseInt(txtManufacturingYear.getText());
        String modelNumber = txtModelNumber.getText();
        String serialNumber = txtSerialNumber.getText();
        int seatCount = Integer.parseInt(txtSeatCount.getText());
        String location = txtCity.getText();
        String certificateNumber = txtCertificateNumber.getText();
        boolean certificateValid =  chkCertValid.isSelected(); 
        boolean certificateExpired = chkCertExp.isSelected();
        boolean vehicleAvailable =  chkAvlYes.isSelected(); 
        boolean vehicleNotAvailable = chkAvlNo.isSelected();

                
        // String certificateExpired = txtCertificateExpDate.getText();
        //boolean vehicleAvailable = 
        
        Car cr = history.addNewCar();
        
        cr.setManufacturer(manufacturer);
        cr.setManufacturingYear(manufacturingYear);
        cr.setModelNumber(modelNumber);
        cr.setSerialNumber(serialNumber);
        cr.setSeatCount(seatCount);
        cr.setLocation(location);
        cr.setCertificateNumber(certificateNumber);
        cr.setCertificateValid(certificateValid);
        cr.setCertificateExpired(certificateExpired);
        cr.setVehicleAvailable(vehicleAvailable);
        cr.setVehicleNotAvailable(vehicleNotAvailable);
        
       // cr.setCertificateExpDate(certificateExpired);
       
        /*  ViewJPanel viewPanel = new ViewJPanel();
    
           DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/DD/YYYY HH:mm:ss");  
           LocalDateTime now = LocalDateTime.now(); 
           viewPanel.lblLastUpdatedOn.setText(dtf.format(now));       
        */
        
        
        JOptionPane.showMessageDialog(this, "New Car added");
        
        txtManufacturer.setText("");
        txtManufacturingYear.setText("");
        txtModelNumber.setText("");
        txtSerialNumber.setText("");
        txtSeatCount.setText("");
        txtCity.setText("");
        txtCertificateNumber.setText("");
        chkCertValid.setSelected(false);
        chkCertExp.setSelected(false);
        chkAvlYes.setSelected(false);
        chkAvlNo.setSelected(false);
   
        
/*        if(rdbtnValid.isSelected()) {
                    rdbtnValid.setSelected(false);
        rdbtnExpired.setSelected(false);
        }        
*/        
        //buttonGroup1.setSelected(buttonGroup1, false);


        
        //txtCertificateExpDate.setText("");
       
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkCertValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCertValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCertValidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox chkAvlNo;
    private javax.swing.JCheckBox chkAvlYes;
    private javax.swing.JCheckBox chkCertExp;
    private javax.swing.JCheckBox chkCertValid;
    private javax.swing.JLabel lblCarAvailable;
    private javax.swing.JLabel lblCertificateExpDate;
    private javax.swing.JLabel lblCertificateNumber;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufacturingYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeatCount;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCertificateNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeatCount;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
