/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshit
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccountDirectory userAccountList;
   
    public ManageCustomerJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        initListners();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
         populateTable();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTextfield = new javax.swing.JTextField();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressTextfield = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        phoneTextfield = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(920, 708));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ADDRESS", "PHONE", "USERNAME", "PASSWORD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 643, 165));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Customers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 530, -1));

        userNameLabel.setText("Username");
        add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        userNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextfieldActionPerformed(evt);
            }
        });
        add(userNameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 259, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));
        add(passwordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 259, -1));

        customerNameLabel.setText("Name");
        add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));
        add(customerNameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 259, -1));

        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        add(addressTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 259, -1));

        btnCreateCustomer.setBackground(new java.awt.Color(255, 102, 102));
        btnCreateCustomer.setText("Create");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });
        add(btnCreateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        btnModify.setBackground(new java.awt.Color(255, 102, 102));
        btnModify.setText("Update");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 82, -1));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 73, -1));

        jLabel6.setText("Phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));
        add(phoneTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 259, -1));

        backjButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backjButton1.setText("< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 30, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextfieldActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        // TODO add your handling code here:
        
          if( userNameTextfield.getText().isEmpty()||passwordTextfield.getText().isEmpty()|| customerNameTextfield.getText().isEmpty() || addressTextfield.getText().isEmpty() || phoneTextfield.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the field details");
            return;
        }
        // if username is unique add the customer to customer Directory
         if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(userNameTextfield.getText())){
            Customer customer = new Customer();
            customer.setName(customerNameTextfield.getText());
            customer.setAddress(addressTextfield.getText());
            customer.setPhone(phoneTextfield.getText());
            customer.setUsername(userNameTextfield.getText());
            customer.setPassword(passwordTextfield.getText());
            customer.setRole(new CustomerRole());
            ecosystem.getUserAccountDirectory().addUserAccount(customer);
            ecosystem.getCustomerDirectory().addCustomer(customer);
            populateTable();
            userNameTextfield.setText("");
            passwordTextfield.setText("");
            customerNameTextfield.setText("");
            addressTextfield.setText("");
            phoneTextfield.setText("");
         }else{
            JOptionPane.showMessageDialog(null, "Username " + userNameTextfield.getText() + " already exists !!!, Please try a new one");
         }
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
           
        int selectedRow = tblCustomer.getSelectedRow();
        if (selectedRow >= 0) {
            System.out.println("selected row" + selectedRow);
            Customer customer = (Customer) tblCustomer.getValueAt(selectedRow, 0);
            System.out.println("item : " + customer);
            customer.setUsername(userNameTextfield.getText());
            customer.setPassword(passwordTextfield.getText());
            customer.setName(customerNameTextfield.getText());
            customer.setPhone(phoneTextfield.getText());
            customer.setAddress(addressTextfield.getText());
            customer.setRole(new CustomerRole());
            populateTable();
            userNameTextfield.setText("");
            passwordTextfield.setText("");
            customerNameTextfield.setText("");
            phoneTextfield.setText("");
            addressTextfield.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int selectedRow = tblCustomer.getSelectedRow();

        if (selectedRow >= 0) {
            Customer customer = (Customer) tblCustomer.getValueAt(selectedRow, 0);
           CustomerDirectory customerDirectory = ecosystem.getCustomerDirectory();
            customerDirectory.removeCustomer(customer);
            JOptionPane.showMessageDialog(null, "Customer   "  + userNameTextfield.getText() + " deleted");
            populateTable();
            customerNameTextfield.setText("");
            phoneTextfield.setText("");
            userNameTextfield.setText("");
            passwordTextfield.setText("");
            addressTextfield.setText("");
           
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_backjButton1ActionPerformed
     private void populateTable() {
        CustomerDirectory customerDirectory = ecosystem.getCustomerDirectory();
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();

        model.setRowCount(0);
        for (Customer customer : customerDirectory.getCustomerList()) {
                    Object[] row = new Object[5];
                    row[0] = customer;
                    row[1] = customer.getAddress();
                    row[2] = customer.getPhone();
                    row[3] = customer.getUsername();
                    row[4] = customer.getPassword();

                    model.addRow(row);
                
            }
        
    }
       private void initListners() {
       tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
           int selectedRow = tblCustomer.getSelectedRow();
             if (selectedRow >= 0) {
                  Customer  customer  = (Customer) tblCustomer.getValueAt(selectedRow, 0);
                 if(customer!=null){
                     display(customer);
                 }
             }
        }
    });
    }
     

    private void display(Customer customer) {
        userNameTextfield.setText(customer.getUsername());
        passwordTextfield.setText(customer.getPassword());
        customerNameTextfield.setText(customer.getName());
        phoneTextfield.setText(customer.getPhone());
        addressTextfield.setText(customer.getAddress());
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextfield;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordTextfield;
    private javax.swing.JTextField phoneTextfield;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextfield;
    // End of variables declaration//GEN-END:variables
}
